"""empty message

Revision ID: 268fe56f4975
Revises: bd5d3385ad93
Create Date: 2020-01-18 19:52:19.202476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268fe56f4975'
down_revision = 'bd5d3385ad93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'genres')
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
