"""empty message

Revision ID: 3deda414e00a
Revises: 4694acb28aae
Create Date: 2020-01-18 22:05:56.643725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3deda414e00a'
down_revision = '4694acb28aae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
