"""empty message

Revision ID: 7e6d9d630bcd
Revises: 268fe56f4975
Create Date: 2020-01-18 19:56:28.494506

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e6d9d630bcd'
down_revision = '268fe56f4975'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('generes', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('Venue', sa.Column('generes', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'generes')
    op.drop_column('Artist', 'generes')
    # ### end Alembic commands ###
