"""empty message

Revision ID: a38c7561c80c
Revises: ca2200b8f7f2
Create Date: 2020-01-16 11:08:35.228042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a38c7561c80c'
down_revision = 'ca2200b8f7f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website_URL', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('genres', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('website_URL', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website_URL')
    op.drop_column('Venue', 'genres')
    op.drop_column('Artist', 'website_URL')
    # ### end Alembic commands ###
